# Agent ports
TRUCK_AGENT_PORT = 8000
LOAD_AGENT_PORT = 8001
WAREHOUSE_AGENT_PORT = 8002
BACKHAUL_AGENT_PORT = 8003
COORDINATOR_PORT = 8005

# Rate caps
MIN_RATE = 0
MAX_RATE = 200

# Map file
DEMO_MAP_FILE = "coordinator/demo_map.json"

# Thresholds
DETOUR_THRESHOLD_KM = 20
NEARBY_RADIUS_KM = 50
TRUCK_SPEED_KMPH = 50
TRUCK_CAPACITY_TONS = 20
DEADLINE_BUFFER_MIN = 15