# Agent ports
TRUCK_AGENT_PORT = 8000
LOAD_AGENT_PORT = 8001
WAREHOUSE_AGENT_PORT = 8002
BACKHAUL_AGENT_PORT = 8003
COORDINATOR_PORT = 8005

# Rate caps (global, can be overridden by admin)
MIN_RATE = 0
MAX_RATE = 200

# Matching and routing constants
DETOUR_THRESHOLD_KM = 20
NEARBY_RADIUS_KM = 50
DEFAULT_TRUCK_SPEED_KMPH = 50
DEADLINE_BUFFER_MIN = 15

# Warehouse fixed dock count
WAREHOUSE_DOCK_COUNT = 5

# Map file – generated by script, not a demo file
MAP_FILE_PATH = "data/map_data.json"

# No session timer, no drive hours